# Generated by Django 5.2.9 on 2025-12-14 23:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('captured_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate_uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gate_type', models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('checkpoint', 'Checkpoint')], default='start', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_hint', models.CharField(blank=True, max_length=200, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('fw_version', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RaceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Klasse',
                'verbose_name_plural': 'Klassen',
                'db_table': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('session_type', models.CharField(choices=[('timed_run', 'Timed Run'), ('multi_lap', 'Multi Lap'), ('open_practice', 'Open Practice')], default='timed_run', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('finished', 'Finished'), ('archived', 'Archived')], default='planned', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['stage', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='operator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_number', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('engine', models.CharField(max_length=50)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('low_confidence', 'Low Confidence'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='core.capture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp_ms', models.BigIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('signal_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='core.gate')),
            ],
            options={
                'ordering': ['timestamp_ms'],
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='core.passage'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_start_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
                ('transponder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('race_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='core.raceclass')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('dnf', 'Did Not Finish'), ('dsq', 'Disqualified'), ('void', 'Void')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('penalty_ms', models.PositiveIntegerField(default=0)),
                ('final_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('start_number_used', models.IntegerField(blank=True, null=True)),
                ('start_number_source', models.CharField(choices=[('driver_default', 'Driver Default'), ('vehicle_default', 'Vehicle Default'), ('manual_override', 'Manual Override'), ('ocr_detected', 'OCR Detected')], default='driver_default', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.session')),
            ],
            options={
                'ordering': ['session', 'driver'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='core.run'),
        ),
        migrations.AddField(
            model_name='passage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='core.session'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_json', models.JSONField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('race_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboards', to='core.raceclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='core.session')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('training', 'Training'), ('qualifying', 'Qualifying'), ('race', 'Race')], default='training', max_length=20)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.event')),
            ],
            options={
                'ordering': ['event', 'stage_order'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.stage'),
        ),
        migrations.AddField(
            model_name='gate',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='core.stage'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('default_start_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.driver')),
                ('race_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.raceclass')),
            ],
            options={
                'ordering': ['driver', 'name'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.vehicle'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['session'], name='core_passag_session_86d435_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['gate'], name='core_passag_gate_id_7e539c_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['timestamp_ms'], name='core_passag_timesta_274004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('session', 'race_class', 'generated_at')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('stage', 'name')},
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['session'], name='core_run_session_299702_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['driver'], name='core_run_driver__116445_idx'),
        ),
    ]
